### ISSUE TITLE
HLS not playing after ad on IOS

### ISSUE THREAD

**Issue by andrefilimono** [kslimani/clappr-google-ima-html5-preroll#12]
In Safary (Iphone) IMA SDK do not dispatch google.ima.AdEvent.Type.CONTENT_RESUME_REQUESTED  event, so method       this._playVideoContent() will not be called. 

Simple workaround is to set:
adsRenderingSettings.restoreCustomPlaybackStateOnAdBreakComplete = false

**Comment by kslimani** [comment]
I tested with iphone5s (Safari, Chrome) and iPad (Safari, Chrome) and i was not able to reproduce this issue. (_the video content is displayed after ad in my tests_).

Thought, for HLS scenario on iOS, the native HTML5 video element is used for playback, and `adsRenderingSettings.restoreCustomPlaybackStateOnAdBreakComplete` set to `false` may improve user experience (_because it should reduce the "latency" time between ad and video content_).

I will change it to false and improve playback state restoration.
Thank you @andrefilimono for report it.

**Comment by kslimani** [comment]
@andrefilimono new release *should* resolve this issue. (_require Clappr 0.2.66 or greater_)

**Comment by andrefilimono** [comment]
Yeah, it works perfectly. 
Thanks!
