### ISSUE TITLE
Issue with Responsive container

### ISSUE THREAD

**Issue by sparebytesltd** [kslimani/clappr-google-ima-html5-preroll#14]
The plugin works perfectly for me. The only issue seems to be with the Responsive container. It destroys the responsive behaviour of:
https://github.com/tobilen/clappr-responsive-container-plugin

**Comment by kslimani** [comment]
@sparebytesltd i released a new version which take account of player resize event. Could you test if it fix your issue ?

**Comment by kslimani** [comment]
This issue should be resolved. Please re-open it if you still have issue with responsive behaviours.
