### ISSUE TITLE
Non linear ad support

### ISSUE THREAD

**Issue by alouane** [kslimani/clappr-google-ima-html5-preroll#15]
Hi there
I think non linear ads are not working properly, is there any support for this ad format in the near future?
Thanks

**Comment by kslimani** [comment]
hi @alouane , i think i could add a partial support (ie: display it as a preroll for a configurable duration before load video content).
But i don't plan in a near future to add support to display non-linear while playing video content.

**Comment by kslimani** [comment]
@alouane i released a new version which partially support non-linear as pre-roll. (currently i have issues for displaying it while content is played).
