### ISSUE TITLE
Companion Ads

### ISSUE THREAD

**Issue by thekendog** [kslimani/clappr-google-ima-html5-preroll#17]
Is there a way to get and display the companion ads for DFP preroll videos?

**Comment by kslimani** [comment]
currently, this plugin does not handle companion ads. But i will take a look and see which feature i can add.

**Comment by kslimani** [comment]
@thekendog according IMA documentation, it seems you can display companion automatically using [Google Publisher Tag](https://developers.google.com/interactive-media-ads/docs/sdks/html5/companions#using-companion-ads-with-google-publisher-tag), maybe it worth a try ?

**Comment by thekendog** [comment]
@kslimani thanks for the help man.  That worked and I'm able to get the companion ads to show now!
