### ISSUE TITLE
Ad error: AdError 1005: The provided ad type: skippablevideo is not supported. 

### ISSUE THREAD

**Issue by HotelBusiness** [kslimani/clappr-google-ima-html5-preroll#23]
I am getting this error when playing a preroll ad on iOS.  The video will not play if the line item is set to 'skippable'.  I found some code on videojs that seems to support skippable ads but do not know if Clappr has this functionality or not.  Help please!

From what I read there, the preroll video must be set as 'playsinline', which I set, but also need the option '**disableCustomPlaybackForIOS10Plus: true**'.  Is there an option like this for Clappr and if so how do I implement it.  Thanks in advance.

**Comment by kslimani** [comment]
I can add an option to this plugin to setup this ima setting.
@ICDpubs do you have any VAST tag to share where i could reproduce the issue on OS mobile device ?

**Comment by HotelBusiness** [comment]
Can I send to you privately.

**Comment by kslimani** [comment]
Just send me an email (in commit messages).

**Comment by kslimani** [comment]
I released a new version. It has a new event to signal when ima sdk is loaded which permit to set custom settings. _(like setDisableCustomPlaybackForIOS10Plus() method)_

**Comment by kslimani** [comment]
Fixed by 7766183b59347229f01709d79bbc47d6a5f3c5fe
