### ISSUE TITLE
Access-Control-Allow-Credentials Error

### ISSUE THREAD

**Issue by AnanthKongu** [kslimani/clappr-google-ima-html5-preroll#6]
Hi,
      I tried this but it gets (XMLHttpRequest cannot load data:text;charset=utf-8,. Credentials flag is 'true', but the 'Access-Control-Allow-Credentials' header is ''. It must be 'true' to allow credentials. Origin 'null' is therefore not allowed access.) error can you please help me...
     Your demo page "https://kslimani.github.io/clappr-google-ima-html5-preroll/" also have the same error.

**Comment by kslimani** [comment]
@AnanthKongu could you please provide more info or take a screenshot ? i cannot reproduce this error on the demo page. Also which are your OS and browser version ?

**Comment by AnanthKongu** [comment]
Hi,
      Can you able to see ads in your demo page? (https://kslimani.github.io/clappr-google-ima-html5-preroll/).
       I can't but in my browser console I got this error
![ads](https://cloud.githubusercontent.com/assets/20402779/21322447/0fe0c138-c63f-11e6-99d2-dc952441a582.png)

**Comment by kslimani** [comment]
@AnanthKongu yes, the demo ad banner on github demo page was displayed with the following configurations :

* Linux Debian Jessie with Google Chrome version 55.0.2883.87 (64-bit)
* Linux Debian Jessie with Firefox version 50.1.0 (64-bit)
* Mac OS Sierra 10.12.2 with Google Chrome 55.0.2883.95 (64-bit)
* Mac OS Sierra 10.12.2 with Firefox version 50.1.0 (64-bit)
* Mac OS Sierra 10.12.2 with Safari version 10.0.2 (12602.3.12.0.1) (64-bit)
* Windows 8 with Google Chrome 55.0.2883.87 (64-bit)

I also have some random error on console for bridge or blocked iframe but the ad is displayed.

Though, i was not able to get your credential error. Please what are your OS and your Browser version ?

**Comment by AnanthKongu** [comment]
I'm using Ubuntu 16.10 & chrome 55.0.2883.87

**Comment by AnanthKongu** [comment]
Yep, I works in another machine, thanks

**Comment by kslimani** [comment]
@AnanthKongu i have installed Ubuntu 16.10 (Yakkety Yak) with ubuntu destop.

I have also installed the `unbuntu-restricted-extras` package _(`sudo apt install unbuntu-restricted-extras`)_

The demo ad banner is displayed with :

* Mozilla Firefox 50.1.0 (64 bits)
* Google Chrome version 55.0.2883.87 (64-bit)

**Comment by AnanthKongu** [comment]
Sorry, it's from my side, I had installed **Chrome Fair AdBlocker App** extension so it blocks the ads, it works for me when I disable it, thanks for your time :)

**Comment by AnanthKongu** [comment]
Hi, When I enable *Adblocker* it'll not play the video also, so I want to skip the ads and play the video directly if they enable *Adblocker*, can you please help me for this....

**Comment by kslimani** [comment]
@AnanthKongu yes, i will fix this today i think, stay tuned.

**Comment by kslimani** [comment]
@AnanthKongu : should be fixed with #7 . It introduce a load timeout for IMA SDK library. I also upgraded plugin version to 0.0.6.

**Comment by AnanthKongu** [comment]
Thank you so much :)
