### ISSUE TITLE
VAST not working

### ISSUE THREAD

**Issue by churu88** [kslimani/clappr-google-ima-html5-preroll#9]
Hi , I'm using this VAST 3.0 in other players, but it doesn't work n clappr with this plugin. Is is compatible with vast 3.0?
This is my vast: https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/40327789/www.lared.am/Home/Home_VideoPreroll&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]

**Comment by kslimani** [comment]
@churu88 : i am always getting an "inventory" response from your VAST tag (ie empty vast response)

Could you provide a tag with non-empty response to be able to debug your issue ?

**Comment by churu88** [comment]
Hi Kslimani, if you check the url in the google video inspector , it works.

https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector

You can also check it working in other player:

www.lared.am

Regards!

**Comment by kslimani** [comment]
@churu88 it seems that response for this tag is not always a video ad. This may be the cause, because the plugin expects a video ad. I will try to find some time this week to check deeper this issue.

**Comment by churu88** [comment]
Thanks Kslimani, you are right I guess this is a campanion ads, but it should work with vast and Ima.
Regards!
